### ISSUE TITLE
jspdf for uts-8 arabic 

### ISSUE THREAD

**Issue by nokarm-88** [ahmednooor/SRS#1]
### thankk you for this amazing project 
**i want to ask you i tired to add arabic uts-8 to downloaded pdf using this [http://raw.githack.com/MrRio/jsPDF/master/docs/](url) but it didn't work so if you can help me with this i'll be greatful ...**

**Comment by ahmednooor** [comment]
I am sorry. I won't be able to help since this issue is related to the `jsPDF` library. You will have to consult with their documentation. Besides this `SRS` project was for learning and experimentation purposes and hence it is not being actively maintained. Thank you.
